config/routes.rb
RailsYeast::Application.routes.draw do

  devise_for :users,
    path: 'u',
    path_names: {
      sign_in: 'in',
      sign_out: 'out',
      password: 'pass',
      confirmation: 'confirm',
      unlock: 'unlock',
      registration: 'reg',
      sign_up: 'new'
    }
  
  resources :contacts, only: [:new, :create]
  resources :resources
  resources :errors
  match 'welcome' => 'resources#welcome'
  match 'about' => 'resources#about'
  match 'privacy' => 'resources#privacy'
  match 'contact' => 'contacts#new'
  root :to => 'resources#welcome'
end

app/views/layouts/_footer.html.erb
<footer>
  <%= render_block do %>
  <%= link_to_nav t('resources.home'), root_path %>
  <%= link_to_nav t('resources.about'), about_path %>
  <%= link_to_nav t('resources.contact'), contact_path %>
  <%= link_to_nav t('resources.privacy'), privacy_path %>
  <% end %>
  <p class="copyright"><%= t('powered_by_html') %></p>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to t('app_name'), root_path, :class => 'pull-left brand active' %>
      <div class="nav-buttons pull-right">
        <% if user_signed_in? %>
          <%= link_to "#{current_user.name} <span class=\"caret\"></span>".html_safe, root_path, class: 'btn dropdown-toggle', 'data-toggle' => 'dropdown' %>
          <ul class="dropdown-menu pull-right" role="menu">
            <%= link_to_nav t("navigation.edit_profile"), edit_registration_path(current_user), icon: 'edit'  %>
            <li class="divider"></li>
            <%= link_to_nav t("navigation.logout"), destroy_user_session_path, icon: 'signout' %>
          </ul>
          
        <% else %>
          <%= link_to t("login"), new_user_session_path, :class => "btn btn-primary"  %>
          <%= link_to t("register"), new_user_registration_path, :class => "btn btn-primary"  %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>" dir="<%= I18n.locale.to_sym == :ar ? 'rtl' : 'ltr' %>">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= t 'app_name' %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= analytics_tag 'UA-28077649-1' %>
  </head>
  <body class="<%= I18n.locale.to_sym == :ar ? 'rtl' : 'ltr' %>">

    <%= render :partial => 'layouts/header' %>

    <div class="primary">
      <div class="primary-container">
      <%= yield :primary %>
    </div><!--/primary-->

    <div class="wrapper clearfix <%= 'with_secondary' if content_for?(:secondary) %>">
      <div class="header">
        <!-- Flash messages -->
        <% [:notice, :error, :alert].each do |level| %>
        <% unless flash[level].blank? %>
        <div class="flash-message <%= flash_class(level) %> fade in">
          <a href="#" data-dismiss="alert" class="close">×</a>
          <%= flash[level] %>
        </div>
        <% end %>
        <% end %>
        <%= yield :header %>
      </div><!--/header-->
      <div class="container content-container">
        <% if content_for? :page_title %>
        <div class="page-header">
          <h1><%= yield :page_title %></h1>
          <% if content_for? :context %>
          <div class="actions context">
            <%= yield :context %>
          </div>
          <% end %>
        </div>
        <% end %>
        <div class="pull-left content">
          <%= yield %>

        </div> <!-- /content -->
        <% if content_for? :secondary %>
        <div class="pull-right secondary">
          <%= yield :secondary %>
        </div><!--/secondary-->
        <% end %>
      </div>

      <%= render :partial => 'layouts/footer' %>
    </div> <!-- /wrapper -->

    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
  </html>

app/views/layouts/errors.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>" dir="<%= I18n.locale.to_sym == :ar ? 'rtl' : 'ltr' %>">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : t(:app_name) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= analytics_tag %>
  </head>
  <body class="<%= I18n.locale.to_sym == :ar ? 'rtl' : 'ltr' %>">
	<%= yield %>
  	<%= flash[:error] %>
    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>